on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "**/*.md"

name: Benchmark
jobs:
  Compare:
    strategy:
      matrix:
        go-version: [1.20.x, 1.21.x, 1.22.x, 1.23.x]
        platforms: ["ubuntu-latest", "macos-latest", "windows-latest"]
    runs-on: "${{ matrix.platform }}"
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ matrix.go-version }}"

      - name: Run Benchmark
        run: go test ./... -bench=. -benchmem -count=5
